import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Academy",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        
        <div className="relative w-full flex items-center justify-center">
          <Toaster position="top-center"/>
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
